senzing-garage/sz-sdk-python-core

src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2configmgr.py, src/senzing/g2configmgr_abstract.py, src/senzing/g2diagnostic.py, src/senzing/g2diagnostic_abstract.py, src/senzing/g2engine.py, src/senzing/g2engine_abstract.py, src/senzing/g2engineflags.py, src/senzing/g2exception.py, src/senzing/g2hasher.py, src/senzing/g2hasher_abstract.py, src/senzing/g2helpers.py, src/senzing/g2product.py, src/senzing/g2product_abstract.py, tests/g2diagnostic_test.py
=> 3.dockter.2

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml, Makefile.darwin, Makefile.linux, Makefile.windows, src/senzing/g2diagnostic.py, tests/g2diagnostic_test.py
=> #3 - Improvements

src/senzing/g2engine.py, src/senzing/g2product.py
=> 3.dockter.4

examples/g2config_add_data_source.py, examples/g2config_add_data_source.txt, examples/g2config_constructor.py, examples/g2config_create_and_close.py, examples/g2config_create_save_load_close.py, examples/g2config_delete_data_source.py, examples/g2config_delete_data_source.txt, examples/g2config_init_and_destroy.py, examples/g2config_list_data_sources.py, examples/g2config_list_data_sources.txt, examples/g2config_load.py, examples/g2config_save.py, examples/g2config_save.txt, src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2config_grpc.py, src/senzing/g2product.py, src/senzing/g2product_abstract.py
=> 3.dockter.6

examples/g2config/add_data_source.txt, examples/g2config/list_data_sources.txt, examples/g2config/save.txt, src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2configmgr.py, src/senzing/g2diagnostic.py, src/senzing/g2hasher.py, src/senzing/g2helpers.py, src/senzing/g2product.py, tests/g2config_test.py, tests/g2diagnostic_test.py
=> 3.dockter.9

src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2configmgr.py, src/senzing/g2configmgr_abstract.py, src/senzing/g2product.py, src/senzing/g2product_abstract.py, src/senzing/g2version.py
=> #3 Updated G2Product

Makefile.linux, src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2configmgr.py, src/senzing/g2configmgr_abstract.py, src/senzing/g2diagnostic.py, src/senzing/g2diagnostic_abstract.py, src/senzing/g2helpers.py, src/senzing/g2product.py, src/senzing/g2product_abstract.py, tests/g2config_test.py, tests/g2configmgr_test.py, tests/g2diagnostic_test.py, tests/g2product_test.py
=> 3.dockter.12

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml, src/senzing/g2config_abstract.py, src/senzing/g2configmgr.py, src/senzing/g2configmgr_abstract.py, src/senzing/g2diagnostic.py, src/senzing/g2helpers.py, src/senzing/g2product_abstract.py, tests/g2configmgr_test.py, tests/g2diagnostic_test.py
=> #3 Decorators for changing ctypes.ArgumentError

docs/source/senzing.rst, src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2configmgr.py, src/senzing/g2configmgr_abstract.py, src/senzing/g2diagnostic.py, src/senzing/g2diagnostic_abstract.py, src/senzing/g2engine.py, src/senzing/g2engine_abstract.py, src/senzing/g2engine_grpc.py, src/senzing/g2product.py, src/senzing/g2product_abstract.py
=> 3.dockter.13

src/senzing/g2config.py, src/senzing/g2config_abstract.py, src/senzing/g2config_grpc.py, src/senzing/g2configmgr.py, src/senzing/g2configmgr_abstract.py, src/senzing/g2configmgr_grpc.py, src/senzing/g2diagnostic.py, src/senzing/g2diagnostic_abstract.py, src/senzing/g2diagnostic_grpc.py, src/senzing/g2engine_grpc.py, src/senzing/g2hasher_grpc.py, src/senzing/g2product.py, src/senzing/g2product_abstract.py, src/senzing/g2product_grpc.py, tests/conftest.py, tests/g2config_test.py, tests/g2configmgr_test.py, tests/g2diagnostic_test.py
=> 3.dockter.17

.github/linters/.yaml-lint.yml, .github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/create-sphinx-documentation.yaml, .github/workflows/dependabot-approve-and-merge.yaml, .github/workflows/flake8.yaml, .github/workflows/isort.yaml, .github/workflows/lint-workflows.yaml, .github/workflows/pylint.yaml, .github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml, .github/workflows/python-code-quality.yaml
Issue number: senzing-factory/build-resources#69
=> senzing-factory/build-resources#69 add linting

.github/workflows/move-pr-to-done-dependabot.yaml, tests/g2diagnostic_test.py
Issue number: senzing-factory/build-resources#108
=> senzing-factory/build-resources#108 move dependabot prs to done on close

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml, pyproject.toml
=> #109 Update to template

CHANGELOG.md, examples/extras/using_abstract_1.py, examples/extras/using_abstract_2.py, examples/misc/individual_classes.py, examples/szengine/a_header_szengine.py, requirements.txt, setup.cfg, src/senzing_core/__init__.py, src/senzing_core/_helpers.py, src/senzing_core/szabstractfactory.py, src/senzing_core/szconfig.py, src/senzing_core/szconfigmanager.py, src/senzing_core/szdiagnostic.py, src/senzing_core/szengine.py, src/senzing_core/szproduct.py, tests/szabstractfactory_test.py, tests/szconfig_test.py, tests/szconfigmanager_test.py, tests/szdiagnostic_test.py, tests/szengine_test.py, tests/szproduct_test.py
=> #136 Rename repository

.github/workflows/bandit.yaml, .github/workflows/build-distribution.yaml, .github/workflows/check-development-dependencies.yaml, .github/workflows/create-sphinx-documentation.yaml, .github/workflows/isort.yaml, .github/workflows/publish-to-pypi.yaml
=> update python versions

tests/szengine_test.py
=> #178 Augment test cases

examples/szproduct/get_version.txt
=> Change the product name to match what we want for Sz.

.github/workflows/create-sphinx-documentation.yaml, .github/workflows/pytest-linux.yaml, docs/README.md, docs/errors.md, docs/examples.md, docs/source/conf.py, docs/source/index.rst, docs/source/modules.rst, docs/source/senzing_core.rst, examples/szengine/add_record.py, examples/szengine/preprocess_record.py, makefiles/linux.mk, requirements.txt, src/senzing_core/szabstractfactory.py, src/senzing_core/szconfig.py, src/senzing_core/szconfigmanager.py, src/senzing_core/szdiagnostic.py, src/senzing_core/szengine.py, src/senzing_core/szproduct.py, tests/szengine_test.py
=> #192 Update documentation

.github/workflows/add-labels-standardized.yaml, .github/workflows/add-to-project-garage-dependabot.yaml, .github/workflows/add-to-project-garage.yaml, .github/workflows/bandit.yaml, .github/workflows/black.yaml, .github/workflows/build-distribution.yaml, .github/workflows/check-development-dependencies.yaml, .github/workflows/create-sphinx-documentation.yaml, .github/workflows/flake8.yaml, .github/workflows/isort.yaml, .github/workflows/mypy.yaml, .github/workflows/publish-to-pypi.yaml, .github/workflows/pylint.yaml, .github/workflows/pytest-linux.yaml
Issue number: senzing-factory/build-resources#179
=> senzing-factory/build-resources#179 add slack notifications

CHANGELOG.md, development-requirements.txt, examples/szengine/why_search.py, examples/szengine/why_search.txt, requirements.txt, setup.cfg, src/senzing_core/szabstractfactory.py, src/senzing_core/szdiagnostic.py, src/senzing_core/szengine.py, tests/szabstractfactory_test.py, tests/szconfig_test.py, tests/szconfigmanager_test.py, tests/szdiagnostic_test.py, tests/szengine_test.py, tests/szproduct_test.py
=> #212 Why Search

.github/workflows/bearer.yaml
=> #237 add bearer

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml
=> #261 nightly cron job for install testing

.github/workflows/pytest-darwin.yaml, .github/workflows/pytest-linux.yaml, .github/workflows/pytest-windows.yaml
=> remove coverage from slack notifications

CHANGELOG.md, examples/szconfig/unregister_data_source.py, setup.cfg
=> #322 - Fix unregister_data_source.py example for szconfig

CHANGELOG.md, Migration.md, requirements.txt, setup.cfg, src/senzing_core/_helpers.py, src/senzing_core/szabstractfactory.py, src/senzing_core/szconfig.py, src/senzing_core/szconfigmanager.py, src/senzing_core/szdiagnostic.py, src/senzing_core/szengine.py, src/senzing_core/szproduct.py
=> #336 - Update migration guide
